sudo: required

services:
  - docker

before_install:
  - docker build -t alesta98/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alesta98/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-north-1-736357313574"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
